Question 1

In [44]:
import numpy as np
import cv2
import sympy

In [3]:
for i in range(1,6):
    print("%d : %d"%(i,i**2))

1 : 1
2 : 4
3 : 9
4 : 16
5 : 25


Question 2

In [46]:
for i in range (1,6):
    if not sympy.isprime(i):
        print( "%d : %d"%(i, i**2))



1 : 1
4 : 16


Question 3

In [51]:
num_arr = np.array([ i for i in range(1,6)])
sqr_arr = num_arr**2
for i,el in enumerate(sqr_arr):
    print("%d : %d"%(i + 1, el) )

1 : 1
2 : 4
3 : 9
4 : 16
5 : 25


Question 4

In [61]:
num_arr = np.array([ i for i in range(1,6)])
filter_arr = []
for i in num_arr:
    if not sympy.isprime(i):
        filter_arr.append(True)
    else:
        filter_arr.append(False)

new_arr = num_arr[filter_arr]
non_prime_sqr = new_arr**2 
for i in range(len(new_arr)):
    print("%d : %d"%(new_arr[i], non_prime_sqr[i]) )



1 : 1
4 : 16


Question 5 (a)

In [11]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[7,8,9,1],[1,2,3,4]])
print(np.dot(A,B))

[[ 9 12 15  9]
 [25 32 39 19]
 [41 52 63 29]]


Question 5 (b)

In [12]:
A = np.array(
    [
        [1,2],
        [3,4],
        [5,6]
    ]
)
B = np.array([
    [3,2],
    [5,4],
    [3,1]
])
print(np.multiply(A,B))

[[ 3  4]
 [15 16]
 [15  6]]


Question 6

In [22]:
rand_arr = np.random.rand(5,7)//0.1
print(rand_arr)
print(rand_arr[3:6,0:2])

[[5. 5. 6. 8. 4. 2. 2.]
 [5. 4. 5. 9. 7. 1. 4.]
 [1. 3. 2. 4. 5. 0. 5.]
 [3. 5. 3. 8. 3. 8. 6.]
 [9. 7. 7. 5. 8. 8. 7.]]
[[3. 5.]
 [9. 7.]]


Question 7 

In [24]:
a = np.array([[1,2,3],[3,4,5]])
b = np.array([1,2,3])
a*b

array([[ 1,  4,  9],
       [ 3,  8, 15]])

In [26]:
a = np.array([[1,2,3],[3,4,5]])
b = np.array([[1,2,3],[4,5,6]])
a*b

array([[ 1,  4,  9],
       [12, 20, 30]])

In [29]:
a = np.array([[1,2,3],[3,4,5]])
b = np.array([4])
a*b

array([[ 4,  8, 12],
       [12, 16, 20]])

Question8

In [43]:
x = np.array([[1,2,3],[2,3,4]])
y = np.append(x,[1,1,1]).reshape(3,3)

In [3]:
m, c = 2 , -4
N = 10
x = np . linspace (0 , N-1, N) . reshape (N, 1 )
sigma = 10
y = m*x + c + np . random . normal (0 , sigma , (N, 1 ) )
X = np.append(x,np.ones(1)).reshape(N+1,1)
print(np.multiply(
    np.multiply(
        np.linalg.inv(
            np.matmul(
                np.transpose(X),
                X
                 )
            ),
        np.transpose(X)
        ),
    y
    ))



[[-0.         -0.00135815 -0.00271629 -0.00407444 -0.00543258 -0.00679073
  -0.00814887 -0.00950702 -0.01086516 -0.01222331 -0.00135815]
 [-0.         -0.03450022 -0.06900044 -0.10350066 -0.13800088 -0.1725011
  -0.20700132 -0.24150155 -0.27600177 -0.31050199 -0.03450022]
 [-0.         -0.03670191 -0.07340383 -0.11010574 -0.14680766 -0.18350957
  -0.22021149 -0.2569134  -0.29361532 -0.33031723 -0.03670191]
 [-0.         -0.04388751 -0.08777501 -0.13166252 -0.17555003 -0.21943754
  -0.26332504 -0.30721255 -0.35110006 -0.39498756 -0.04388751]
 [ 0.          0.02787357  0.05574714  0.08362072  0.11149429  0.13936786
   0.16724143  0.195115    0.22298858  0.25086215  0.02787357]
 [-0.         -0.03598632 -0.07197265 -0.10795897 -0.14394529 -0.17993161
  -0.21591794 -0.25190426 -0.28789058 -0.3238769  -0.03598632]
 [ 0.          0.01995018  0.03990037  0.05985055  0.07980074  0.09975092
   0.11970111  0.13965129  0.15960148  0.17955166  0.01995018]
 [ 0.          0.03222101  0.06444202  0.0

Question 9

In [25]:
def hyper_square(s):
    n= 0
    a = s
    while True:
        if 1<=a<=100 and n%2==0:
            break
        a = a/10
        n+=1 

    # print(a,n)

    return ((-190/(a+20))+10)*(10**(n/2))
        
        

In [26]:
def newton_root(s,err=10**(-5)):
    s0 = hyper_square(s)
    count = 0
    while True:
        s1 = (s0+s/s0)/2
        #print(s1)
        if abs(s1-s0) <= err:break
        s0 = s1
    return s1
    
lst = [64,75,100,1600]
for i in lst:
    print(newton_root(i))

8.000000000000094
8.660254037844386
10.0
40.0


Question 10

In [33]:
img = cv2.imread(r'gal_gaussian.png')
gausblur = cv2.GaussianBlur(img,(5,5),0)
cv2.namedWindow('Original Image', cv2.WINDOW_AUTOSIZE)
cv2.imshow('Original Image',img)
cv2.namedWindow('Gaussian Effect', cv2.WINDOW_AUTOSIZE)
cv2.imshow('Gaussian Effect', gausblur)
cv2.waitKey(0)
cv2.destroyAllWindows()


Question 11

In [37]:
img2 = cv2.imread(r'gal_sandp.png')
medimg = cv2.medianBlur(img2,5)
cv2.namedWindow('Original Image', cv2.WINDOW_AUTOSIZE)
cv2.imshow('Original Image',img2)
cv2.namedWindow('Salt and Pepper Filter', cv2.WINDOW_AUTOSIZE)
cv2.imshow('Salt and Pepper Filter', medimg)
cv2.waitKey(0)
cv2.destroyAllWindows()


Question 12

In [39]:
greyimg = np.zeros((40,60), dtype = np.uint8)
greyimg[0:21, 30:61] = 125
cv2.namedWindow('Greyscale Image', cv2.WINDOW_AUTOSIZE)
cv2.imshow('Greyscale Image',greyimg)
cv2.waitKey(0)
cv2.destroyAllWindows()


Question 13

In [40]:
bbimg = np.zeros((40,60,3), dtype = np.uint8)
bbimg[21:41, 0:31] = [218,24,132]
cv2.namedWindow('Barbie Pink Color Image', cv2.WINDOW_AUTOSIZE)
cv2.imshow('Barbie Pink Color Image',bbimg)
cv2.waitKey(0)
cv2.destroyAllWindows()


Question 14

In [41]:
darkimg = cv2.imread(r'tom_dark.jpg')
cv2.namedWindow('Dark Image', cv2.WINDOW_AUTOSIZE)
cv2.imshow('Dark Image',darkimg)
brightimg = darkimg +80
cv2.namedWindow('Bright Image', cv2.WINDOW_AUTOSIZE)
cv2.imshow('Bright Image', brightimg)
cv2.waitKey(0)
cv2.destroyAllWindows()